uploads = []
generated = []

[[outputs]]
id = "PaOgP44Rbhy6qfV0K0hax"
uri = "file://bot/assets/example_brief.pdf"
type = "pdf"
title = "Краткий разбор (пример)"

[[outputs]]
id = "Aqn0scHcD1nc18X35uKMx"
uri = "file://bot/assets/example_full.pdf"
type = "pdf"
title = "Полный разбор (пример)"
